# File: cluster-setup.yml (Optimized for Speed and Cache Efficiency)
---
- name: ⚙️ 1. Prepare All Nodes for Kubernetes Installation (Prerequisites)
  hosts: kube_master, kube_workers
  become: yes
  gather_facts: no # Avoids slow initial fact gathering
  tasks:
    - name: Perform initial apt update and install essential tools (Faster update)
      ansible.builtin.apt:
        name: 
          - curl 
          - gnupg # Required for the APT key management later
          - docker.io
        state: present
        update_cache: yes # Only perform update here to save time

    - name: Ensure kernel modules and sysctl params are set
      ansible.builtin.shell: |
        modprobe overlay
        modprobe br_netfilter
        sysctl net.bridge.bridge-nf-call-iptables=1
      args:
        executable: /bin/bash

    - name: Ensure Docker is running
      ansible.builtin.systemd_service:
        name: docker
        state: started
        enabled: yes

    - name: Disable Swap (Kubernetes Requirement)
      ansible.builtin.shell: |
        swapoff -a
        sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
      register: swap_status
      changed_when: swap_status.stdout != ""
      tags: swap

- name: 🚀 2. Install Kubeadm Tools on All Nodes
  hosts: kube_master, kube_workers
  become: yes
  tasks:
    # --- FIX: ADD KUBERNETES APT REPOSITORY ---
    - name: Add Kubernetes APT key
      ansible.builtin.shell: |
        curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | \
        gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      args:
        executable: /bin/bash

    - name: Add Kubernetes repository to sources list
      ansible.builtin.apt_repository:
        repo: 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /'
        state: present
        filename: kubernetes
        # We rely on the initial update_cache or the auto-update mechanism

    # --- FINAL INSTALLATION ---
    - name: Install Kubeadm, Kubelet, and Kubectl (Now packages are available)
      ansible.builtin.apt:
        name: 
          - kubelet
          - kubeadm
          - kubectl
        state: present
        # Since we added a new repository, we must update the cache here!
        update_cache: yes 
        allow_downgrade: yes 
        dpkg_options: 'force-confdef,force-confold'

- name: 🏷️ 3. Label Worker Node for App Scheduling
  hosts: kube_workers
  become: no 
  gather_facts: false
  tasks:
    - name: Label Worker Node with 'node-type=app-worker'
      ansible.builtin.shell: |
        kubectl label node {{ inventory_hostname }} node-type=app-worker --overwrite
      register: label_output
      changed_when: "'labeled' in label_output.stdout"

- name: ✅ 4. Final Verification
  hosts: kube_master, kube_workers
  gather_facts: false
  tasks:
    - name: Test SSH connection post-setup
      ansible.builtin.ping: