# File: deploy.yml (Minor efficiency updates)
---
- name: Deploy Docker Container via Ansible
  hosts: web_servers
  become: yes # Use privilege escalation (sudo) on the remote machine
  gather_facts: false
  tasks:
    - name: Ensure deployment directory exists
      ansible.builtin.file:
        path: /home/deploy/app_deployment # Changed user to 'deploy' (Best practice)
        state: directory
        owner: deploy # Changed user to 'deploy'
        group: docker # Changed group to 'docker' for socket access
        mode: '0755'

    - name: Copy docker-compose.yml to remote host
      ansible.builtin.copy:
        src: docker-compose.yml 
        dest: /home/deploy/app_deployment/docker-compose.yml
        owner: deploy
        group: docker

    - name: Deploy and restart container via Docker Compose
      ansible.builtin.command:
        cmd: docker compose up -d --force-recreate
        chdir: /home/deploy/app_deployment # Use chdir instead of shell 'cd'
      # NOTE: Pull is now handled implicitly by up --force-recreate or can be a separate task.
      # Removed 'shell' module and replaced with 'command' for safety.